---
- name: Create Nextcloud MariaDB database
  mysql_db:
    name: "{{ nextcloud_database_name }}"
    collation: "utf8mb4_general_ci"
    encoding: "utf8mb4"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add Nextcloud MariaDB user account
  mysql_user:
    name: "{{ nextcloud_database_user }}"
    password: "{{ nextcloud_database_password }}"
    priv: "{{ nextcloud_database_name }}.*:ALL"
    append_privs: True
    host: "{{ item.host }}"
    state: "present"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - host: localhost
    - host: "%"
