---
# Force rebuilding of image, but only run when config files have changed
- name: Build nextcloud docker image
  docker_image:
    name: "nextcloud"
    build:
      path: "{{ nextcloud_image_dir }}"
      pull: yes
    source: build
    force_source: yes
  when: nextcloud_register_config.changed or nextcloud_force_rebuild

- name: Install nextcloud container (with ldap support)
  docker_container:
    name: "nextcloud"
    image: nextcloud
    state: "{{ nextcloud_state }}"
    restart: "{{ nextcloud_register_config.changed }}"
    restart_policy: "{{ nextcloud_restart_policy }}"
    published_ports: "{{ nextcloud_ports }}"
    volumes: "{{ nextcloud_volumes }}"
    env: "{{ nextcloud_environment }}"
    etc_hosts: >
      {
        "{{ nextcloud_collabora_fqdn }}": "{{ nextcloud_docker_ip }}",
        "{{ nextcloud_fqdn }}": "{{ nextcloud_docker_ip }}"
      }
  when:
    - nextcloud_redis_host != "redis"

- name: Install nextcloud container (without ldap support)
  docker_container:
    name: "nextcloud"
    image: nextcloud
    state: "{{ nextcloud_state }}"
    restart: "{{ nextcloud_register_config.changed }}"
    restart_policy: "{{ nextcloud_restart_policy }}"
    published_ports: "{{ nextcloud_ports }}"
    links:
      - "redis:redis"
    volumes: "{{ nextcloud_volumes }}"
    env: "{{ nextcloud_environment }}"
    etc_hosts: >
      {
        "{{ nextcloud_collabora_fqdn }}": "{{ nextcloud_docker_ip }}",
        "{{ nextcloud_fqdn }}": "{{ nextcloud_docker_ip }}"
      }
  when:
    - nextcloud_redis_host == "redis"

# Find out ip of docker nextcloud container
- name: Find out ip of docker nextcloud container
  shell: "docker inspect nextcloud | grep -o -m1 -P '(?<=IPAddress\": \").*(?=\",)'"
  register: nextcloud_ip

# ToDo: This is not the nicest way to handle it, but it works for now..
- name: Wait for docker container to spin up
  wait_for:
    host: "{{ nextcloud_ip.stdout }}"
    port: 80
    delay: 3

# We use nextcloud autoconfig to add our custom nextcloud config.
# Unfortunately, this does not completly finish the installation process,
# see https://github.com/nextcloud/nextcloud-snap/issues/208
- name: Ping nextcloud install to finish installation
  command: "curl -L http://{{ nextcloud_ip.stdout }}"
  when: nextcloud_register_config.changed or nextcloud_force_rebuild

# Run occ upgrade after nextcloud config files have changed
- name: Run occ upgrade
  command: docker exec --user www-data nextcloud php occ upgrade
  when: nextcloud_register_config.changed or nextcloud_force_rebuild

- name: Add trusted domains to nextcloud config
  command: >
    docker exec --user www-data nextcloud
    php occ config:system:set trusted_domains {{ item.0 }}
    --value={{ item.1 }}
  with_indexed_items:
    - "localhost"
    - "{{ nextcloud_fqdn }}"
