---
- name: Copy nginx block (vhost) config file to available sites
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/sites-available/{{ nextcloud_fqdn }}.conf"
  with_items:
    - nginx.conf
  notify: "reload nginx"

- name: Enable nginx block config
  file:
    src: "/etc/nginx/sites-available/{{ nextcloud_fqdn }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nextcloud_fqdn }}.conf"
    state: link
  notify: "reload nginx"
