FROM nextcloud:{{ nextcloud_version }}-apache

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        # smbclient \
        supervisor \
        # svg support
        libmagickcore-6.q16-6-extra \
    ; \
    rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    \
    savedAptMark="$(apt-mark showmanual)"; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libbz2-dev \
        # libsmbclient-dev \
    ; \
    \

    docker-php-ext-install \
        bz2 \
    ; \
    # pecl install smbclient; \
    # docker-php-ext-enable smbclient; \
    \
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
    apt-mark auto '.*' > /dev/null; \
    apt-mark manual $savedAptMark; \
    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
        | awk '/=>/ { print $3 }' \
        | sort -u \
        | xargs -r dpkg-query -S \
        | cut -d: -f1 \
        | sort -u \
        | xargs -rt apt-mark manual; \
    \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p \
    /usr/share/man/man1 \
    /var/log/supervisord \
    /var/run/supervisord \
;

COPY supervisord.conf /etc/supervisor/supervisord.conf
COPY nextcloud.config.php /usr/src/nextcloud/config/nextcloud.config.php
COPY apache-pretty-urls.config.php /usr/src/nextcloud/config/apache-pretty-urls.config.php
COPY apcu.config.php /usr/src/nextcloud/config/apcu.config.php
COPY redis.config.php /usr/src/nextcloud/config/redis.config.php
COPY apps.config.php /usr/src/nextcloud/config/apps.config.php
COPY i18n.config.php /usr/src/nextcloud/config/i18n.config.php
COPY mail.config.php /usr/src/nextcloud/config/mail.config.php
COPY log.config.php /usr/src/nextcloud/config/log.config.php
COPY skeletonfiles.config.php /usr/src/nextcloud/config/skeletonfiles.config.php

ENV NEXTCLOUD_UPDATE=1

CMD ["/usr/bin/supervisord"]
